/* js/data-tables.js — Reine Inhalts-Tabellen (datengetrieben, DOM-frei),
   aus data.js ausgelagert (Phase 27 – Modularisierung). MUSS vor js/data.js
   geladen werden. Bereitstellung als window/globalThis.GameDataTables. */
(function () {
  'use strict';
  var root = (typeof window !== 'undefined') ? window : globalThis;
  var T = root.GameDataTables = root.GameDataTables || {};

  T.creatures = [
    // Schleim-Linie
    { id: 'schleim', name: 'Schleim', icon: '🟦', rank: 'E', line: 'Schleim', role: 'Magie',
      summon: { magie: 30 }, statMod: { mag: 1.3, lp: 1.2, ang: 0.7 }, skill: 'verschlinger',
      desc: 'Formloser Anfang – mit großem Potenzial.',
      evolvesTo: [{ to: 'magieschleim', req: { named: true } }] },
    { id: 'magieschleim', name: 'Magie-Schleim', icon: '🔵', rank: 'D', line: 'Schleim', role: 'Magie',
      statMod: { mag: 1.5, lp: 1.2, ang: 0.7 },
      desc: 'Ein Schleim voller Magicules.',
      evolvesTo: [{ to: 'hochschleim', req: { level: 18, seelen: 30 } }] },
    { id: 'hochschleim', name: 'Hoch-Schleim', icon: '🟣', rank: 'C', line: 'Schleim', role: 'Magie',
      statMod: { mag: 1.6, lp: 1.3 },
      desc: 'Ein hochentwickelter, denkender Schleim.',
      evolvesTo: [{ to: 'tyrannenschleim', req: { level: 30, seelen: 120, herrscherStufe: 2 } }] },
    { id: 'tyrannenschleim', name: 'Tyrannen-Schleim', icon: '🌌', rank: 'B', line: 'Schleim', role: 'Magie',
      statMod: { mag: 1.7, lp: 1.4, ang: 1.1 }, skill: 'tyrann',
      desc: 'Ein Schleimfürst mit verheerender Magie.', evolvesTo: [] },

    // Goblin-Linie
    { id: 'goblin', name: 'Goblin', icon: '👺', rank: 'E', line: 'Goblin', role: 'Kampf',
      summon: { magie: 24 }, statMod: { ang: 1.0 },
      desc: 'Schwacher, aber zahlreicher Krieger.',
      evolvesTo: [{ to: 'hobgoblin', req: { named: true } }] },
    { id: 'hobgoblin', name: 'Hobgoblin', icon: '👹', rank: 'D', line: 'Goblin', role: 'Kampf',
      statMod: { ang: 1.1, ver: 1.1, lp: 1.1 }, skill: 'raubtier',
      desc: 'Ein benannter Goblin – größer und diszipliniert.',
      evolvesTo: [{ to: 'goblin_lord', req: { level: 20, seelen: 40 } },
                  { to: 'goblin_schamane', req: { level: 20, seelen: 40 } }] },
    { id: 'goblin_lord', name: 'Goblin-Lord', icon: '🛡️', rank: 'C', line: 'Goblin', role: 'Kampf',
      statMod: { ang: 1.2, ver: 1.2, lp: 1.2 },
      desc: 'Anführer einer Goblin-Streitmacht.',
      evolvesTo: [{ to: 'goblin_koenig', req: { level: 32, seelen: 140, herrscherStufe: 2 } }] },
    { id: 'goblin_koenig', name: 'Goblin-König', icon: '👑', rank: 'B', line: 'Goblin', role: 'Kampf',
      statMod: { ang: 1.3, ver: 1.3, lp: 1.3 }, skill: 'tyrann',
      desc: 'Herrscher über ein ganzes Goblin-Volk.', evolvesTo: [] },

    // Wolf-Linie
    { id: 'schreckenswolf', name: 'Schreckenswolf', icon: '🐺', rank: 'D', line: 'Wolf', role: 'Kampf',
      summon: { magie: 55 }, statMod: { tmp: 1.5, ang: 1.2, ver: 0.8, mag: 0.5 },
      desc: 'Schneller Rudeljäger.',
      evolvesTo: [{ to: 'sturmwolf', req: { named: true } },
                  { to: 'mondwolf', req: { named: true } }] },
    { id: 'sturmwolf', name: 'Sturmwolf', icon: '🌩️', rank: 'C', line: 'Wolf', role: 'Kampf',
      statMod: { tmp: 1.6, ang: 1.3, ver: 0.9, mag: 0.6 }, skill: 'raubtier',
      desc: 'Reitet auf dem Wind, schnell wie ein Blitz.',
      evolvesTo: [{ to: 'sternwolf', req: { level: 30, seelen: 120 } }] },
    { id: 'sternwolf', name: 'Sternwolf', icon: '✴️', rank: 'B', line: 'Wolf', role: 'Kampf',
      statMod: { tmp: 1.8, ang: 1.4, mag: 0.8 },
      desc: 'Ein legendärer Wolf mit Sternenglanz.', evolvesTo: [] },

    // Oger / Kijin-Linie
    { id: 'oger', name: 'Oger', icon: '👿', rank: 'C', line: 'Oger', role: 'Kampf',
      summon: { magie: 120, seelen: 10 }, statMod: { ang: 1.4, lp: 1.3, ver: 1.1, mag: 0.5 },
      desc: 'Roher, mächtiger Nahkämpfer.',
      evolvesTo: [{ to: 'kijin', req: { named: true } }] },
    { id: 'kijin', name: 'Kijin', icon: '🥷', rank: 'B', line: 'Oger', role: 'Kampf',
      statMod: { ang: 1.4, ver: 1.2, mag: 1.0, tmp: 1.1 }, skill: 'tyrann',
      desc: 'Ein erwachter Oger-Krieger mit Verstand und Magie.',
      evolvesTo: [{ to: 'oni', req: { level: 45, seelen: 260, herrscherStufe: 3 } }] },
    { id: 'oni', name: 'Oni', icon: '👹', rank: 'A', line: 'Oger', role: 'Kampf',
      statMod: { ang: 1.6, ver: 1.3, mag: 1.1, tmp: 1.2 },
      desc: 'Ein dämonischer Oni von erschütternder Stärke.', evolvesTo: [] },

    // Echsenmensch / Drachenmensch-Linie
    { id: 'echsenmensch', name: 'Echsenmensch', icon: '🦎', rank: 'D', line: 'Echse', role: 'Kampf',
      summon: { magie: 60 }, statMod: { ver: 1.3, lp: 1.2 },
      desc: 'Zäher Sumpfkrieger.',
      evolvesTo: [{ to: 'drachenmensch', req: { named: true } },
                  { to: 'sumpfschamane', req: { named: true } }] },
    { id: 'drachenmensch', name: 'Drachenmensch', icon: '🐲', rank: 'C', line: 'Echse', role: 'Kampf',
      statMod: { ver: 1.3, ang: 1.2, mag: 1.1, lp: 1.2 }, skill: 'stahlhaut',
      desc: 'Trägt das Blut der Drachen in sich.',
      evolvesTo: [{ to: 'drachenfuerst', req: { level: 34, seelen: 160 } }] },
    { id: 'drachenfuerst', name: 'Drachenfürst', icon: '🐉', rank: 'B', line: 'Echse', role: 'Kampf',
      statMod: { ver: 1.4, ang: 1.3, mag: 1.2, lp: 1.3 },
      desc: 'Ein Fürst der Drachenmenschen.', evolvesTo: [] },

    // Ork-Linie
    { id: 'ork', name: 'Ork', icon: '🐗', rank: 'D', line: 'Ork', role: 'Kampf',
      summon: { magie: 50 }, statMod: { lp: 1.4, ang: 1.1, mag: 0.6 },
      desc: 'Unermüdlicher, hungriger Krieger.',
      evolvesTo: [{ to: 'ork_lord', req: { level: 22, seelen: 50 } }] },
    { id: 'ork_lord', name: 'Ork-Lord', icon: '🪓', rank: 'C', line: 'Ork', role: 'Kampf',
      statMod: { lp: 1.5, ang: 1.3 }, skill: 'tyrann',
      desc: 'Führt eine gefräßige Horde an.',
      evolvesTo: [{ to: 'ork_katastrophe', req: { level: 48, seelen: 300, herrscherStufe: 3 } }] },
    { id: 'ork_katastrophe', name: 'Ork-Katastrophe', icon: '☄️', rank: 'A', line: 'Ork', role: 'Kampf',
      statMod: { lp: 1.7, ang: 1.5 },
      desc: 'Eine wandelnde Katastrophe, die alles verschlingt.', evolvesTo: [] },

    // Skelett / Lich-Linie (Untote)
    { id: 'skelett', name: 'Skelett', icon: '💀', rank: 'E', line: 'Untot', role: 'Magie',
      summon: { magie: 26 }, statMod: { ang: 0.9, mag: 0.9, lp: 0.8 },
      desc: 'Wiederbelebte Knochen.',
      evolvesTo: [{ to: 'knochenmagier', req: { named: true } }] },
    { id: 'knochenmagier', name: 'Knochenmagier', icon: '🧙', rank: 'D', line: 'Untot', role: 'Magie',
      statMod: { mag: 1.6, lp: 0.8 },
      desc: 'Ein Skelett, das die Totenmagie erlernt hat.',
      evolvesTo: [{ to: 'elder_lich', req: { level: 24, seelen: 60 } }] },
    { id: 'elder_lich', name: 'Elder Lich', icon: '☠️', rank: 'C', line: 'Untot', role: 'Magie',
      statMod: { mag: 1.9, lp: 0.9 }, skill: 'magieader',
      desc: 'Ein uralter, mächtiger Totenbeschwörer.',
      evolvesTo: [{ to: 'untotenfuerst', req: { level: 50, seelen: 340, herrscherStufe: 3 } }] },
    { id: 'untotenfuerst', name: 'Untoten-Fürst', icon: '👑', rank: 'A', line: 'Untot', role: 'Magie',
      statMod: { mag: 2.1, lp: 1.0, ang: 1.0 }, skill: 'untoter_wille',
      desc: 'Ein uralter Fürst der Untoten – Schrecken der Lebenden.', evolvesTo: [] },

    // Zombie / Todesritter-Linie
    { id: 'zombie', name: 'Zombie', icon: '🧟', rank: 'E', line: 'Untot', role: 'Kampf',
      summon: { magie: 22 }, statMod: { lp: 1.4, ang: 0.9, mag: 0.3, tmp: 0.4 },
      desc: 'Langsam, aber zäh und billig.',
      evolvesTo: [{ to: 'ghul', req: { named: true } }] },
    { id: 'ghul', name: 'Ghul', icon: '🧟‍♂️', rank: 'D', line: 'Untot', role: 'Kampf',
      statMod: { lp: 1.4, ang: 1.1, tmp: 0.6 },
      desc: 'Ein schnellerer, hungriger Untoter.',
      evolvesTo: [{ to: 'todesritter', req: { level: 26, seelen: 70 } }] },
    { id: 'todesritter', name: 'Todesritter', icon: '🗡️', rank: 'C', line: 'Untot', role: 'Kampf',
      statMod: { ang: 1.4, ver: 1.4, lp: 1.2 }, skill: 'untoter_wille',
      desc: 'Ein gefallener Ritter in untoter Rüstung.',
      evolvesTo: [{ to: 'todespaladin', req: { level: 38, seelen: 180 } },
                  { to: 'seelenwaechter', req: { level: 38, seelen: 180 } }] },
    { id: 'todespaladin', name: 'Todespaladin', icon: '⚜️', rank: 'B', line: 'Untot', role: 'Kampf',
      statMod: { ang: 1.5, ver: 1.5, lp: 1.3, mag: 1.1 },
      desc: 'Ein Champion der Untoten-Armee.', evolvesTo: [] },

    // Imp / Dämon-Linie
    { id: 'imp', name: 'Imp', icon: '😈', rank: 'D', line: 'Dämon', role: 'Magie',
      summon: { magie: 65, seelen: 5 }, statMod: { mag: 1.4, tmp: 1.2, lp: 0.8 },
      desc: 'Ein kleiner, tückischer Dämon.',
      evolvesTo: [{ to: 'daemon', req: { named: true, level: 20 } }] },
    { id: 'daemon', name: 'Dämon', icon: '👿', rank: 'B', line: 'Dämon', role: 'Magie',
      statMod: { mag: 1.4, ang: 1.2, tmp: 1.1 }, skill: 'magieader',
      desc: 'Ein vollwertiger Dämon mit gefährlicher Magie.',
      evolvesTo: [{ to: 'erzdaemon', req: { level: 52, seelen: 360 } }] },
    { id: 'erzdaemon', name: 'Erzdämon', icon: '🦇', rank: 'A', line: 'Dämon', role: 'Magie',
      statMod: { mag: 1.6, ang: 1.3, tmp: 1.2 },
      desc: 'Ein Hochadliger der Dämonenwelt.',
      evolvesTo: [{ to: 'daemonenfuerst', req: { level: 66, seelen: 900, herrscherStufe: 4 } }] },
    { id: 'daemonenfuerst', name: 'Dämonenfürst', icon: '🔱', rank: 'S', line: 'Dämon', role: 'Magie',
      statMod: { mag: 1.8, ang: 1.5, tmp: 1.3 }, skill: 'tyrann',
      desc: 'Einer der furchterregendsten Dämonen überhaupt.', evolvesTo: [] },

    // Vampir-Linie
    { id: 'vampir', name: 'Vampir', icon: '🧛', rank: 'C', line: 'Vampir', role: 'Kampf',
      summon: { magie: 140, seelen: 20 }, statMod: { mag: 1.3, ang: 1.2, tmp: 1.2 },
      desc: 'Eleganter Blutsauger mit dunkler Magie.',
      evolvesTo: [{ to: 'echter_vampir', req: { named: true } }] },
    { id: 'echter_vampir', name: 'Echter Vampir', icon: '🦇', rank: 'B', line: 'Vampir', role: 'Kampf',
      statMod: { mag: 1.4, ang: 1.3, tmp: 1.3 }, skill: 'magieader',
      desc: 'Ein wahrer Adliger der Nacht.',
      evolvesTo: [{ to: 'blutfuerstin', req: { level: 50, seelen: 340, herrscherStufe: 3 } }] },
    { id: 'blutfuerstin', name: 'Blutfürstin', icon: '🩸', rank: 'A', line: 'Vampir', role: 'Kampf',
      statMod: { mag: 1.6, ang: 1.4, tmp: 1.4 },
      desc: 'Eine uralte Vampirfürstin von tödlicher Schönheit.', evolvesTo: [] },

    // Golem-Linie
    { id: 'lehmgolem', name: 'Lehmgolem', icon: '🗿', rank: 'D', line: 'Golem', role: 'Verteidigung',
      summon: { magie: 48, material: 20 }, statMod: { lp: 1.6, ver: 1.6, ang: 1.0, mag: 0.2, tmp: 0.3 },
      desc: 'Eine wandelnde Festung aus Lehm.',
      evolvesTo: [{ to: 'eisengolem', req: { level: 18, material: 60 } }] },
    { id: 'eisengolem', name: 'Eisengolem', icon: '🛡️', rank: 'C', line: 'Golem', role: 'Verteidigung',
      statMod: { lp: 1.7, ver: 1.8, ang: 1.1, mag: 0.3, tmp: 0.3 }, skill: 'stahlhaut',
      desc: 'Ein Koloss aus gehärtetem Eisen.',
      evolvesTo: [{ to: 'magistahlgolem', req: { level: 34, material: 200, seelen: 80 } },
                  { to: 'runengolem', req: { level: 34, material: 200, seelen: 80 } }] },
    { id: 'magistahlgolem', name: 'Magistahl-Golem', icon: '🤖', rank: 'B', line: 'Golem', role: 'Verteidigung',
      statMod: { lp: 1.9, ver: 2.0, ang: 1.3, mag: 0.6 },
      desc: 'Ein unzerstörbarer Wächter aus Magistahl.', evolvesTo: [] },

    // Insekten-Linie
    { id: 'ruestungskaefer', name: 'Rüstungskäfer', icon: '🪲', rank: 'D', line: 'Insekt', role: 'Verteidigung',
      summon: { magie: 46 }, statMod: { ver: 1.5, lp: 1.2, mag: 0.4 },
      desc: 'Ein gepanzertes Rieseninsekt.',
      evolvesTo: [{ to: 'insektoid_krieger', req: { named: true } }] },
    { id: 'insektoid_krieger', name: 'Insektoid-Krieger', icon: '🦗', rank: 'C', line: 'Insekt', role: 'Kampf',
      statMod: { ver: 1.4, ang: 1.3, tmp: 1.1 }, skill: 'stahlhaut',
      desc: 'Ein diszipliniertes Insekten-Soldatenwesen.',
      evolvesTo: [{ to: 'insektenkoenigin', req: { level: 50, seelen: 340, herrscherStufe: 3 } }] },
    { id: 'insektenkoenigin', name: 'Insektenkönigin', icon: '👑', rank: 'A', line: 'Insekt', role: 'Kampf',
      statMod: { ver: 1.6, ang: 1.4, mag: 1.2, lp: 1.4 },
      desc: 'Mutter eines ganzen Schwarms.', evolvesTo: [] },

    // Drachen-Linie (Endgame)
    { id: 'drakeling', name: 'Drakeling', icon: '🐊', rank: 'B', line: 'Drache', role: 'Kampf',
      summon: { magie: 600, seelen: 60 }, statMod: { lp: 1.5, ang: 1.4, ver: 1.3, mag: 1.4, tmp: 1.2 },
      desc: 'Ein junger Drache mit gewaltigem Potenzial.',
      evolvesTo: [{ to: 'drache', req: { level: 45, seelen: 300 } }] },
    { id: 'drache', name: 'Drache', icon: '🐉', rank: 'A', line: 'Drache', role: 'Kampf',
      statMod: { lp: 1.6, ang: 1.5, ver: 1.4, mag: 1.5, tmp: 1.3 }, skill: 'drachenwut',
      desc: 'Ein ausgewachsener Drache – Naturgewalt.',
      evolvesTo: [{ to: 'sturmdrache', req: { level: 65, seelen: 800, herrscherStufe: 4 } }] },
    { id: 'sturmdrache', name: 'Sturmdrache', icon: '🌪️', rank: 'S', line: 'Drache', role: 'Kampf',
      statMod: { lp: 1.7, ang: 1.6, ver: 1.5, mag: 1.7, tmp: 1.5 },
      desc: 'Ein Sturmherr, der den Himmel beherrscht.',
      evolvesTo: [{ to: 'katastrophendrache', req: { level: 85, seelen: 2500, herrscherStufe: 5 } }] },
    { id: 'katastrophendrache', name: 'Katastrophendrache', icon: '🌋', rank: 'SS', line: 'Drache', role: 'Kampf',
      statMod: { lp: 1.9, ang: 1.8, ver: 1.6, mag: 1.9, tmp: 1.6 }, skill: 'drachenwut',
      desc: 'Ein wahrer Drache von Weltuntergangs-Klasse.', evolvesTo: [] },

    // Fee / Geist-Linie (Magie)
    { id: 'fee', name: 'Fee', icon: '🧚', rank: 'E', line: 'Geist', role: 'Magie',
      summon: { magie: 28 }, statMod: { mag: 1.4, tmp: 1.1, lp: 0.7, ang: 0.6 },
      desc: 'Ein flüchtiger Funke reiner Magicules.',
      evolvesTo: [{ to: 'elementargeist', req: { named: true } }] },
    { id: 'elementargeist', name: 'Elementargeist', icon: '🌟', rank: 'D', line: 'Geist', role: 'Magie',
      statMod: { mag: 1.5, tmp: 1.2, lp: 0.8 },
      desc: 'Ein Geist, der ein Element verkörpert.',
      evolvesTo: [{ to: 'hochgeist', req: { level: 30, seelen: 120 } }] },
    { id: 'hochgeist', name: 'Hochgeist', icon: '💫', rank: 'C', line: 'Geist', role: 'Magie',
      statMod: { mag: 1.7, tmp: 1.3, lp: 0.9 }, skill: 'magieader',
      desc: 'Ein mächtiger, uralter Naturgeist.',
      evolvesTo: [{ to: 'geisterkoenigin', req: { level: 46, seelen: 280, herrscherStufe: 3 } }] },
    { id: 'geisterkoenigin', name: 'Geisterkönigin', icon: '👑', rank: 'B', line: 'Geist', role: 'Magie',
      statMod: { mag: 1.9, tmp: 1.4, lp: 1.1 }, skill: 'feenzauber',
      desc: 'Titanin der Feenwelt, Gebieterin der Geister.', evolvesTo: [] },

    // Harpyie / Greif-Linie (Wind, Kampf)
    { id: 'harpyie', name: 'Harpyie', icon: '🪶', rank: 'D', line: 'Greif', role: 'Kampf',
      summon: { magie: 52 }, statMod: { tmp: 1.5, ang: 1.2, ver: 0.7, mag: 0.6 },
      desc: 'Geflügelte Jägerin der Lüfte.',
      evolvesTo: [{ to: 'sturmklaue', req: { named: true } }] },
    { id: 'sturmklaue', name: 'Sturmklaue', icon: '🌬️', rank: 'C', line: 'Greif', role: 'Kampf',
      statMod: { tmp: 1.6, ang: 1.3, ver: 0.8 }, skill: 'raubtier',
      desc: 'Reißt im Sturzflug aus dem Wind heraus an.',
      evolvesTo: [{ to: 'greif', req: { level: 34, seelen: 160 } }] },
    { id: 'greif', name: 'Greif', icon: '🦅', rank: 'B', line: 'Greif', role: 'Kampf',
      statMod: { tmp: 1.7, ang: 1.4, ver: 1.0, mag: 0.7 }, skill: 'windschneide',
      desc: 'Edles Mischwesen aus Adler und Löwe.',
      evolvesTo: [{ to: 'donnervogel', req: { level: 50, seelen: 340, herrscherStufe: 3 } }] },
    { id: 'donnervogel', name: 'Donnervogel', icon: '⚡', rank: 'A', line: 'Greif', role: 'Kampf',
      statMod: { tmp: 1.9, ang: 1.5, mag: 1.0, ver: 1.0 },
      desc: 'Ein Gewittersturm in Vogelgestalt.', evolvesTo: [] },

    // Baumhirte / Pflanzen-Linie (Erde, Verteidigung)
    { id: 'sproessling', name: 'Sprössling', icon: '🌱', rank: 'E', line: 'Baumhirte', role: 'Verteidigung',
      summon: { magie: 34, material: 10 }, statMod: { lp: 1.4, ver: 1.3, ang: 0.6, mag: 0.5 },
      desc: 'Ein erwachtes, junges Pflanzenwesen.',
      evolvesTo: [{ to: 'baumhirte', req: { named: true } }] },
    { id: 'baumhirte', name: 'Baumhirte', icon: '🌿', rank: 'D', line: 'Baumhirte', role: 'Verteidigung',
      statMod: { lp: 1.6, ver: 1.5, ang: 0.8, mag: 0.6 }, skill: 'lebensbaum',
      desc: 'Ein wandelnder Hüter des Waldes.',
      evolvesTo: [{ to: 'alter_ent', req: { level: 28, material: 120 } }] },
    { id: 'alter_ent', name: 'Alter Ent', icon: '🌳', rank: 'C', line: 'Baumhirte', role: 'Verteidigung',
      statMod: { lp: 1.9, ver: 1.7, mag: 0.8, ang: 1.0 }, skill: 'stahlhaut',
      desc: 'Ein uralter Baumriese voller Lebenskraft.',
      evolvesTo: [{ to: 'weltenesche', req: { level: 48, seelen: 300, herrscherStufe: 3 } }] },
    { id: 'weltenesche', name: 'Weltenesche', icon: '🪵', rank: 'B', line: 'Baumhirte', role: 'Verteidigung',
      statMod: { lp: 2.1, ver: 1.9, mag: 1.0, ang: 1.0 }, skill: 'lebensbaum',
      desc: 'Ein Weltenbaum, dessen Wurzeln das Reich tragen.', evolvesTo: [] },

    // Phönix-Linie (Feuer, Endgame)
    { id: 'glutvogel', name: 'Glutvogel', icon: '🐣', rank: 'B', line: 'Phönix', role: 'Kampf',
      summon: { magie: 550, seelen: 50 }, statMod: { mag: 1.5, tmp: 1.4, ang: 1.3, lp: 1.2 },
      desc: 'Ein junger Feuervogel voller Glut.',
      evolvesTo: [{ to: 'phoenix', req: { level: 45, seelen: 300 } }] },
    { id: 'phoenix', name: 'Phönix', icon: '🔥', rank: 'A', line: 'Phönix', role: 'Kampf',
      statMod: { mag: 1.6, tmp: 1.5, ang: 1.4, lp: 1.3 }, skill: 'wiedergeburt',
      desc: 'Ein Phönix, der aus seiner eigenen Asche aufersteht.',
      evolvesTo: [{ to: 'sonnenphoenix', req: { level: 65, seelen: 800, herrscherStufe: 4 } }] },
    { id: 'sonnenphoenix', name: 'Sonnenphönix', icon: '☀️', rank: 'S', line: 'Phönix', role: 'Kampf',
      statMod: { mag: 1.7, tmp: 1.6, ang: 1.4, lp: 1.4 }, skill: 'wiedergeburt',
      desc: 'Ein Phönix, dessen Glut der Sonne gleicht.',
      evolvesTo: [{ to: 'ewiger_phoenix', req: { level: 85, seelen: 2500, herrscherStufe: 5 } }] },
    { id: 'ewiger_phoenix', name: 'Ewiger Phönix', icon: '🌅', rank: 'SS', line: 'Phönix', role: 'Kampf',
      statMod: { mag: 2.0, tmp: 1.8, ang: 1.6, lp: 1.5 }, skill: 'wiedergeburt',
      desc: 'Ein unsterblicher Phönix von Katastrophen-Klasse.', evolvesTo: [] },

    // Weitere Völker des Jura-Waldes und der angrenzenden Reiche
    { id: 'kobold', name: 'Kobold', icon: '🐕', rank: 'E', line: 'Kobold', role: 'Kampf',
      summon: { magie: 28 }, statMod: { tmp: 1.25, ang: 0.9, lp: 0.9 },
      desc: 'Ein wachsamer hundeartiger Waldläufer.', evolvesTo: [{ to: 'kobold_jaeger', req: { named: true } }] },
    { id: 'kobold_jaeger', name: 'Kobold-Jäger', icon: '🏹', rank: 'D', line: 'Kobold', role: 'Kampf',
      statMod: { tmp: 1.45, ang: 1.15, ver: 0.85 }, skill: 'jaeger',
      desc: 'Ein schneller Späher, der jede Fährte liest.', evolvesTo: [{ to: 'kobold_hauptmann', req: { level: 28, seelen: 110 } }] },
    { id: 'kobold_hauptmann', name: 'Kobold-Hauptmann', icon: '🎖️', rank: 'C', line: 'Kobold', role: 'Kampf',
      statMod: { tmp: 1.4, ang: 1.3, ver: 1.1 }, skill: 'kriegstanz',
      desc: 'Ein disziplinierter Hauptmann der Waldwache.', evolvesTo: [] },

    { id: 'hasenmensch', name: 'Hasenmensch', icon: '🐇', rank: 'E', line: 'Hasenmensch', role: 'Kampf',
      summon: { magie: 32 }, statMod: { tmp: 1.5, ang: 0.85, lp: 0.85 },
      desc: 'Ein flinker Bewohner der östlichen Ebenen.', evolvesTo: [{ to: 'mondhase', req: { named: true } }] },
    { id: 'mondhase', name: 'Mondhase', icon: '🌙', rank: 'D', line: 'Hasenmensch', role: 'Magie',
      statMod: { tmp: 1.6, mag: 1.2, ver: 0.8 }, skill: 'jaeger',
      desc: 'Webt Mondlicht in rasche Illusionsschritte.', evolvesTo: [{ to: 'bestienritter', req: { level: 29, seelen: 120 } }] },
    { id: 'bestienritter', name: 'Bestienritter', icon: '🐰', rank: 'C', line: 'Hasenmensch', role: 'Kampf',
      statMod: { tmp: 1.65, ang: 1.25, ver: 1.0 }, skill: 'kriegstanz',
      desc: 'Eine blitzschnelle Elite der Bestienvölker.', evolvesTo: [] },

    { id: 'tengu', name: 'Tengu', icon: '👺', rank: 'C', line: 'Tengu', role: 'Magie',
      summon: { magie: 115, seelen: 8 }, statMod: { tmp: 1.45, mag: 1.25, ang: 1.0 },
      desc: 'Ein stolzer Berggeist, der auf Windströmen reist.', evolvesTo: [{ to: 'windtengu', req: { named: true } }] },
    { id: 'windtengu', name: 'Wind-Tengu', icon: '🪭', rank: 'B', line: 'Tengu', role: 'Magie',
      statMod: { tmp: 1.65, mag: 1.45, ang: 1.1 }, skill: 'windschneide',
      desc: 'Seine Fächerhiebe schneiden selbst durch Stahl.', evolvesTo: [{ to: 'tengu_aeltester', req: { level: 50, seelen: 330, herrscherStufe: 3 } }] },
    { id: 'tengu_aeltester', name: 'Tengu-Ältester', icon: '🌪️', rank: 'A', line: 'Tengu', role: 'Magie',
      statMod: { tmp: 1.7, mag: 1.6, ang: 1.15 }, skill: 'magieader',
      desc: 'Ein uralter Meister der Himmels- und Windmagie.', evolvesTo: [] },

    { id: 'meerling', name: 'Meerling', icon: '🧜', rank: 'D', line: 'Meervolk', role: 'Verteidigung',
      summon: { magie: 64 }, statMod: { lp: 1.2, ver: 1.25, mag: 1.0 },
      desc: 'Ein amphibischer Wächter aus den Küstenreichen.', evolvesTo: [{ to: 'meerkrieger', req: { named: true } }] },
    { id: 'meerkrieger', name: 'Meervolk-Krieger', icon: '🔱', rank: 'C', line: 'Meervolk', role: 'Verteidigung',
      statMod: { lp: 1.35, ver: 1.4, mag: 1.1 }, skill: 'stahlhaut',
      desc: 'Beherrscht Schildwall und Gezeitenmagie.', evolvesTo: [{ to: 'meerfuerst', req: { level: 38, seelen: 190 } }] },
    { id: 'meerfuerst', name: 'Fürst der Gezeiten', icon: '🌊', rank: 'B', line: 'Meervolk', role: 'Magie',
      statMod: { lp: 1.4, ver: 1.35, mag: 1.6 }, skill: 'arkane_resonanz',
      desc: 'Ein Befehlshaber, dem die Gezeiten gehorchen.', evolvesTo: [] },

    // --- Verzweigungsformen (alternative Evolutionspfade) ---
    { id: 'goblin_schamane', name: 'Goblin-Schamane', icon: '🔮', rank: 'C', line: 'Goblin', role: 'Magie',
      statMod: { mag: 1.6, lp: 1.1, ang: 0.8 }, skill: 'magieader',
      desc: 'Ein Goblin, der die Geistermagie meistert.',
      evolvesTo: [{ to: 'goblin_koenig', req: { level: 32, seelen: 140, herrscherStufe: 2 } }] },
    { id: 'mondwolf', name: 'Mondwolf', icon: '🌙', rank: 'C', line: 'Wolf', role: 'Magie',
      statMod: { mag: 1.4, tmp: 1.3, ver: 0.8, ang: 0.9 }, skill: 'magieader',
      desc: 'Ein Wolf, der das Mondlicht zu Magie webt.',
      evolvesTo: [{ to: 'sternwolf', req: { level: 30, seelen: 120 } }] },
    { id: 'sumpfschamane', name: 'Sumpfschamane', icon: '🐍', rank: 'C', line: 'Echse', role: 'Magie',
      statMod: { mag: 1.5, ver: 1.1, lp: 1.1 }, skill: 'magieader',
      desc: 'Ein Echsenmensch, der die Sumpfgeister beschwört.',
      evolvesTo: [{ to: 'drachenfuerst', req: { level: 34, seelen: 160 } }] },
    { id: 'seelenwaechter', name: 'Seelenwächter', icon: '🕯️', rank: 'B', line: 'Untot', role: 'Verteidigung',
      statMod: { ver: 1.5, mag: 1.3, lp: 1.3, ang: 1.0 }, skill: 'untoter_wille',
      desc: 'Ein untoter Hüter, der Seelen und Festung bewahrt.', evolvesTo: [] },
    { id: 'runengolem', name: 'Runengolem', icon: '🪬', rank: 'B', line: 'Golem', role: 'Magie',
      statMod: { mag: 1.6, ver: 1.5, lp: 1.5, ang: 1.0 }, skill: 'magieader',
      desc: 'Ein Golem, in dessen Runen arkane Macht pulsiert.', evolvesTo: [] }
  ];
})();
